# æ„å»º VitePress ç«™ç‚¹å¹¶å°†å…¶éƒ¨ç½²åˆ° GitHub Pages çš„ç¤ºä¾‹å·¥ä½œæµç¨‹
#
name: ğŸˆ Deploy VitePress site to Pages

on:
  # åœ¨é’ˆå¯¹ `main` åˆ†æ”¯çš„æ¨é€ä¸Šè¿è¡Œã€‚å¦‚æœä½ 
  # ä½¿ç”¨ `master` åˆ†æ”¯ä½œä¸ºé»˜è®¤åˆ†æ”¯ï¼Œè¯·å°†å…¶æ›´æ”¹ä¸º `master`
  push:
    branches: [main]

  # å…è®¸ä½ ä» Actions é€‰é¡¹å¡æ‰‹åŠ¨è¿è¡Œæ­¤å·¥ä½œæµç¨‹
  workflow_dispatch:

# è®¾ç½® GITHUB_TOKEN çš„æƒé™ï¼Œä»¥å…è®¸éƒ¨ç½²åˆ° GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# åªå…è®¸åŒæ—¶è¿›è¡Œä¸€æ¬¡éƒ¨ç½²ï¼Œè·³è¿‡æ­£åœ¨è¿è¡Œå’Œæœ€æ–°é˜Ÿåˆ—ä¹‹é—´çš„è¿è¡Œé˜Ÿåˆ—
# ä½†æ˜¯ï¼Œä¸è¦å–æ¶ˆæ­£åœ¨è¿›è¡Œçš„è¿è¡Œï¼Œå› ä¸ºæˆ‘ä»¬å¸Œæœ›å…è®¸è¿™äº›ç”Ÿäº§éƒ¨ç½²å®Œæˆ
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # æ„å»ºå·¥ä½œ
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ† Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # å¦‚æœæœªå¯ç”¨ lastUpdatedï¼Œåˆ™ä¸éœ€è¦
      - uses: pnpm/action-setup@v3 # å¦‚æœä½¿ç”¨ pnpmï¼Œè¯·å–æ¶ˆæ³¨é‡Š
        with:
          version: 8
      # - uses: oven-sh/setup-bun@v1 # å¦‚æœä½¿ç”¨ Bunï¼Œè¯·å–æ¶ˆæ³¨é‡Š
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm # æˆ– npm / yarn
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: pnpm install # æˆ– npm ci / yarn install / bun install
      - name: Build with VitePress
        run: pnpm docs:build # npm run docs:build  / yarn docs:build / bun run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # éƒ¨ç½²å·¥ä½œ
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: ğŸ‰ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


# # æ„å»º VitePress ç«™ç‚¹å¹¶å°†å…¶éƒ¨ç½²åˆ° GitHub Pages çš„ç¤ºä¾‹å·¥ä½œæµç¨‹
# #
# name: ğŸˆ éƒ¨ç½²æ–‡æ¡£

# on:
#   # åœ¨é’ˆå¯¹ `main` åˆ†æ”¯çš„æ¨é€ä¸Šè¿è¡Œã€‚å¦‚æœä½ 
#   # ä½¿ç”¨ `master` åˆ†æ”¯ä½œä¸ºé»˜è®¤åˆ†æ”¯ï¼Œè¯·å°†å…¶æ›´æ”¹ä¸º `master`
#   push:
#     branches: [main]

#   # å…è®¸ä½ ä» Actions é€‰é¡¹å¡æ‰‹åŠ¨è¿è¡Œæ­¤å·¥ä½œæµç¨‹
#   workflow_dispatch:

# # è®¾ç½® GITHUB_TOKEN çš„æƒé™ï¼Œä»¥å…è®¸éƒ¨ç½²åˆ° GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# # åªå…è®¸åŒæ—¶è¿›è¡Œä¸€æ¬¡éƒ¨ç½²ï¼Œè·³è¿‡æ­£åœ¨è¿è¡Œå’Œæœ€æ–°é˜Ÿåˆ—ä¹‹é—´çš„è¿è¡Œé˜Ÿåˆ—
# # ä½†æ˜¯ï¼Œä¸è¦å–æ¶ˆæ­£åœ¨è¿›è¡Œçš„è¿è¡Œï¼Œå› ä¸ºæˆ‘ä»¬å¸Œæœ›å…è®¸è¿™äº›ç”Ÿäº§éƒ¨ç½²å®Œæˆ
# concurrency:
#   group: pages
#   cancel-in-progress: false

# jobs:
#   # æ„å»ºå·¥ä½œ
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: ğŸ† Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0 # å¦‚æœæœªå¯ç”¨ lastUpdatedï¼Œåˆ™ä¸éœ€è¦
#       - uses: pnpm/action-setup@v3 # å¦‚æœä½¿ç”¨ pnpmï¼Œè¯·å–æ¶ˆæ³¨é‡Š
#         with:
#           version: 8
#       # - uses: oven-sh/setup-bun@v1 # å¦‚æœä½¿ç”¨ Bunï¼Œè¯·å–æ¶ˆæ³¨é‡Š
#       - name: è®¾ç½® Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: pnpm # æˆ– npm / yarn
#       - name: Setup Pages
#         uses: actions/configure-pages@v4
#       - name: Install dependencies
#         run: pnpm install # æˆ– npm ci / yarn install / bun install
#       - name: Build with VitePress
#         run: pnpm docs:build # npm run docs:build  / yarn docs:build / bun run docs:build
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: docs/.vitepress/dist
#       - name: ğŸ‰ Deploy to GitHub Pages
#         id: deployment
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           # è¿™æ˜¯æ–‡æ¡£éƒ¨ç½²åˆ°çš„åˆ†æ”¯åç§°
#           branch: gh-pages
#           folder: docs/.vitepress/dist
#           token: ${{ secrets.TOKEN }}
#           repository-name: cunyu1943/cunyu1943.github.io

#   # éƒ¨ç½²å·¥ä½œ
#   # deploy:
#   #   environment:
#   #     name: github-pages
#   #     url: ${{ steps.deployment.outputs.page_url }}
#   #   needs: build
#   #   runs-on: ubuntu-latest
    
